const ADMIN_KEYS={school:'school_config_demo',periods:'periods_demo',catalogs:'catalogs_demo'};
const defaultCatalogs={materias:['Matemáticas','Física','Cálculo','Estadística','Programación','Álgebra'],carreras:['IAEV','ICM','IRC','ITIID','LTF','ISA'],grupos:['IAEV-PA-08','IAEV-PA-07','ITIID-IA-02','ITIID-SM-02','ISA-SA-06','ICM-CYM-03','IRC-MPR-02','LTF 08','SW 28'],motivos:['Motivos académicos','Motivos familiares','Motivos personales','Motivos sociales']};
const ADMIN_DEFAULT_PERIOD='Septiembre-Diciembre 2026';
const admin$=s=>document.querySelector(typeof s==='string'&&s.startsWith('#')?s:`#${s}`);
let centralAdminData=null;
function adminRead(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch(e){return fallback}}
function adminWrite(key,value){localStorage.setItem(key,JSON.stringify(value)); if(__sharedReady&&(key===ADMIN_KEYS.catalogs||key===ADMIN_KEYS.periods)) window.__pushShared?.()}
let __sharedReady=false, __sharedTimer=null;
function __applyShared(d){if(centralAdminData||!d||d.type!=='asesorias-data')return; try{localStorage.setItem('asesorias_demo',JSON.stringify(d.records||[]));localStorage.setItem('alumnos_demo',JSON.stringify(d.students||[]));const localUsers=adminUsers();if(!localUsers.length)localStorage.setItem('asesor_users_demo',JSON.stringify(d.users||[]));localStorage.setItem('catalogs_demo',JSON.stringify(d.catalogs||{}));localStorage.setItem('periods_demo',JSON.stringify(d.periods||[]));if(d.school)localStorage.setItem('school_config_demo',JSON.stringify(d.school));}catch(e){} __sharedReady=true; renderAll(); applySchool(); fillAdminFilters(); fillPeriodSelect('dashboardPeriod',false);}
function __requestShared(){const f=document.getElementById('dataBridge'); if(f?.contentWindow) f.contentWindow.postMessage({type:'asesorias-request',action:'get'},'*')}
window.__pushShared=()=>{const f=document.getElementById('dataBridge');if(!f?.contentWindow)return;f.contentWindow.postMessage({type:'asesorias-request',action:'setCatalogs',catalogs:adminRead(ADMIN_KEYS.catalogs,defaultCatalogs)},'*');f.contentWindow.postMessage({type:'asesorias-request',action:'setPeriods',periods:adminRead(ADMIN_KEYS.periods,[ADMIN_DEFAULT_PERIOD])},'*');f.contentWindow.postMessage({type:'asesorias-request',action:'setUsers',users:adminUsers()},'*');};
window.addEventListener('message',e=>{if(e.data?.type==='asesorias-data')__applyShared(e.data);if(e.data?.type==='asesorias-bridge-ready'){__sharedReady=true;window.__pushShared?.();}});
function adminRecords(){if(centralAdminData)return centralAdminData.advisories;try{return JSON.parse(localStorage.getItem('asesorias_demo')||'[]')}catch(e){return []}}
function adminStudents(){if(centralAdminData)return centralAdminData.students;try{return JSON.parse(localStorage.getItem('alumnos_demo')||'[]')}catch(e){return []}}
function adminUsers(){if(centralAdminData)return centralAdminData.users;try{return JSON.parse(localStorage.getItem('asesor_users_demo')||'[]')}catch(e){return []}}
function allAdvisors(){return adminUsers().filter(user=>user.rol!=='admin'&&user.role!=='admin')}
function registeredAdvisors(){return adminUsers().filter(user=>user.rol!=='admin'&&user.role!=='admin'&&user.activo!==false)}
async function saveAdvisor(event){event?.preventDefault();const form=admin$('#add-asesores'),nameInput=admin$('#newAdvisorName'),userInput=admin$('#newAdvisorUser'),passwordInput=admin$('#newAdvisorPassword'),nombre=String(nameInput?.value||'').trim(),usuario=String(userInput?.value||'').trim(),password=String(passwordInput?.value||''),message=admin$('#advisorFormMessage');if(message){message.textContent='';message.className='advisor-form-message'}if(!nombre||!usuario){const missing=!nombre&&!usuario?'el nombre completo y el usuario':!nombre?'el nombre completo':'el usuario';if(message){message.textContent=`Falta capturar ${missing}.`;message.classList.add('error')}alert(`Falta capturar ${missing}.`);(!nombre?nameInput:userInput)?.focus();return}const button=admin$('#saveAdvisorBtn');if(button){button.disabled=true;button.textContent='Guardando...'}try{const response=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({fullName:nombre,username:usuario,password})});const payload=await response.json();if(!response.ok){if(message){message.textContent=payload.message||'No fue posible agregar al asesor.';message.classList.add('error')}return}await loadAdminData();form?.reset();if(message){message.textContent=`Asesor ${nombre} agregado correctamente con el usuario ${usuario}.`;message.classList.add('success')}alert(`Asesor ${nombre} agregado correctamente. Ya puede iniciar sesión con el usuario ${usuario}.`)}catch(error){if(message){message.textContent='No fue posible comunicarse con el servidor.';message.classList.add('error')}}finally{if(button){button.disabled=false;button.textContent='Agregar asesor'}}}
function schoolConfig(){const cfg=adminRead(ADMIN_KEYS.school,{schoolName:'NOMBRE DE LA INSTITUCIÓN',footer:'© 2025 Registro de Asesorías Académicas. Todos los derechos reservados.',version:'1.6.0'});cfg.version='1.6.0';return cfg}
function catalogs(){const c=adminRead(ADMIN_KEYS.catalogs,defaultCatalogs);return {...defaultCatalogs,...c}}
function periods(){if(centralAdminData?.periods?.length)return centralAdminData.periods.map(period=>period.name);const p=adminRead(ADMIN_KEYS.periods,[ADMIN_DEFAULT_PERIOD]);return Array.from(new Set(p.filter(Boolean)))}
function activePeriodName(){return centralAdminData?.periods?.find(period=>period.active!==false)?.name||periods()[0]||ADMIN_DEFAULT_PERIOD}
function adminPeriods(){return centralAdminData?.periods||[]}
function fmtAdmin(m){m=Number(m)||0;return `${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`}
function escapeHTML(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function selectedPeriod(){return admin$('#dashboardPeriod')?.value||activePeriodName()}
function periodRecords(period=selectedPeriod()){return adminRecords().filter(x=>x.periodo===period)}
function rangeMatch(x,r){const d=new Date(x.creado),n=new Date();if(r==='all')return true;if(r==='day')return d.toDateString()===n.toDateString();if(r==='week'){const w=new Date(n);w.setDate(n.getDate()-n.getDay());w.setHours(0,0,0,0);return d>=w}if(r==='month')return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear();return true}
function getAdminFiltered(){const rec=adminRecords();const period=admin$('adminPeriodFilter').value,range=admin$('adminRangeFilter').value,advisor=admin$('adminAdvisorFilter').value,career=admin$('adminCareerFilter').value,group=admin$('adminGroupFilter').value,subject=admin$('adminSubjectFilter').value,reason=admin$('adminReasonFilter').value,search=admin$('adminStudentSearch').value.trim().toLowerCase();return rec.filter(x=>(period==='all'||x.periodo===period)&&rangeMatch(x,range)&&(advisor==='all'||x.asesor===advisor)&&(career==='all'||x.carrera===career)&&(group==='all'||x.grupo===group)&&(subject==='all'||x.materia===subject)&&(reason==='all'||x.motivo===reason)&&(!search||String(x.matricula).toLowerCase().includes(search)||String(x.nombre).toLowerCase().includes(search)))}
function fillSelect(id,items,allLabel){const e=admin$(id);if(!e)return;const old=e.value;e.innerHTML=`<option value="all">${allLabel}</option>`+items.filter(x=>x&&x!=='Seleccione').map(x=>`<option value="${escapeHTML(x)}">${escapeHTML(x)}</option>`).join('');if(Array.from(e.options).some(o=>o.value===old))e.value=old}
function fillPeriodSelect(id,includeAll=false){const e=admin$(id);if(!e)return;const old=e.value;const p=periods();e.innerHTML=(includeAll?'<option value="all">Todos los cuatrimestres</option>':'')+p.map(x=>`<option value="${escapeHTML(x)}">${escapeHTML(x)}</option>`).join('');if(Array.from(e.options).some(o=>o.value===old))e.value=old;else if(!includeAll)e.value=activePeriodName()}
function fillAdminFilters(){const r=adminRecords(),c=catalogs();const uniq=k=>Array.from(new Set(r.map(x=>x[k]).filter(Boolean))).sort((a,b)=>String(a).localeCompare(String(b),'es')),advisorUsers=registeredAdvisors().map(user=>user.usuario).filter(Boolean).sort((a,b)=>String(a).localeCompare(String(b),'es'));fillPeriodSelect('adminPeriodFilter',true);fillSelect('adminAdvisorFilter',advisorUsers,'Todos');fillSelect('adminCareerFilter',uniq('carrera'),'Todas');fillSelect('adminGroupFilter',uniq('grupo'),'Todos');fillSelect('adminSubjectFilter',c.materias,'Todas');fillSelect('adminReasonFilter',c.motivos,'Todos')}
function sumBy(rows,key){const out={};rows.forEach(x=>{const k=x[key]||'Sin dato';out[k]??={n:0,m:0};out[k].n++;out[k].m+=Number(x.duracionMinutos)||0});return out}
function renderRows(map,keys,empty='Sin registros.'){const entries=Object.entries(map);if(!entries.length)return `<tr><td colspan="${keys.length}">${empty}</td></tr>`;return entries.sort((a,b)=>b[1].m-a[1].m).map(([k,v])=>`<tr>${keys.map((_,i)=>i===0?`<td>${escapeHTML(k)}</td>`:i===1?`<td>${v.n}</td>`:`<td>${(v.m/60).toFixed(2)}</td>`).join('')}</tr>`).join('')}
function renderDashboard(){const p=selectedPeriod(),r=periodRecords(p),students=new Set(r.map(x=>x.matricula).filter(Boolean)),advisors=registeredAdvisors(),subjects=new Set(r.map(x=>x.materia).filter(x=>x&&x!=='Seleccione')),referrals=r.filter(x=>String(x.psico||'').toLowerCase().includes('sí')||String(x.psico||'').toLowerCase().includes('si')).length;admin$('#students').textContent=students.size||(!r.length&&p===ADMIN_DEFAULT_PERIOD?adminStudents().length:0);admin$('#sessions').textContent=r.length;admin$('#hours').textContent=(r.reduce((t,x)=>t+(Number(x.duracionMinutos)||0),0)/60).toFixed(2);admin$('#advisors').textContent=advisors.length;admin$('#subjectsUsed').textContent=subjects.size;admin$('#referrals').textContent=referrals}
function renderStatistics(){const r=periodRecords(selectedPeriod());const bySubject=sumBy(r,'materia'),byReason=sumBy(r,'motivo'),byAdvisor=sumBy(r,'asesor'),groupMap={};r.forEach(x=>{const k=`${x.carrera||'Sin carrera'} · ${x.grupo||'Sin grupo'}`;groupMap[k]??={n:0,m:0};groupMap[k].n++;groupMap[k].m+=Number(x.duracionMinutos)||0});const refMap={'Sí':{n:0,m:0},'No':{n:0,m:0}};r.forEach(x=>{const yes=String(x.psico||'').toLowerCase().startsWith('s');const k=yes?'Sí':'No';refMap[k].n++;refMap[k].m+=Number(x.duracionMinutos)||0});admin$('#bySubject').innerHTML=renderRows(bySubject,['k','n','m']);admin$('#byReason').innerHTML=renderRows(byReason,['k','n','m']);admin$('#byAdvisor').innerHTML=renderRows(byAdvisor,['k','n','m']);admin$('#byGroup').innerHTML=Object.entries(groupMap).sort((a,b)=>b[1].m-a[1].m).map(([k,v])=>{const parts=k.split(' · ');return `<tr><td>${escapeHTML(parts[0])}</td><td>${escapeHTML(parts[1]||'')}</td><td>${v.n}</td><td>${(v.m/60).toFixed(2)}</td></tr>`}).join('')||'<tr><td colspan="4">Sin registros.</td></tr>';admin$('#byReferral').innerHTML=renderRows(refMap,['k','n','m']);const all=adminRecords(),pm={};periods().forEach(name=>{pm[name]={n:0,m:0}});all.forEach(x=>{const k=x.periodo||'Sin cuatrimestre';pm[k]??={n:0,m:0};pm[k].n++;pm[k].m+=Number(x.duracionMinutos)||0});admin$('#byPeriod').innerHTML=renderRows(pm,['k','n','m'])}
function renderStudentSummary(){const r=periodRecords(selectedPeriod()),stu={};r.forEach(x=>{const k=x.matricula||'Sin matrícula';stu[k]??={nombre:x.nombre,n:0,m:0};stu[k].n++;stu[k].m+=Number(x.duracionMinutos)||0});const rows=Object.entries(stu).sort((a,b)=>b[1].m-a[1].m);admin$('#byStudent').innerHTML=rows.length?rows.map(([k,v])=>`<tr><td>${escapeHTML(k)}</td><td>${escapeHTML(v.nombre)}</td><td>${v.n}</td><td>${(v.m/60).toFixed(2)}</td></tr>`).join(''):'<tr><td colspan="4">Sin registros en este cuatrimestre.</td></tr>'}
function renderAdminReport(){const rows=getAdminFiltered(),body=admin$('#adminHistory tbody');body.innerHTML=rows.map(x=>`<tr><td>${escapeHTML(x.fecha)}</td><td>${escapeHTML(x.inicio)}</td><td>${escapeHTML(x.fin)}</td><td>${escapeHTML(x.matricula)}</td><td>${escapeHTML(x.nombre)}</td><td>${escapeHTML(x.sexo)}</td><td>${escapeHTML(x.carrera)}</td><td>${escapeHTML(x.grupo)}</td><td>${escapeHTML(x.materia)}</td><td>${escapeHTML(x.motivo)}</td><td>${escapeHTML(x.comentarios)}</td><td>${escapeHTML(x.asesor)}</td><td>${fmtAdmin(x.duracionMinutos)}</td><td>${escapeHTML(x.psico)}</td><td>${escapeHTML(x.periodo)}</td></tr>`).join('');admin$('#reportCount').textContent=`${rows.length} registro${rows.length===1?'':'s'}`;admin$('#reportHours').textContent=`${(rows.reduce((t,x)=>t+(Number(x.duracionMinutos)||0),0)/60).toFixed(2)} horas`}
function renderCatalogStudents(filter=''){const q=filter.toLowerCase();const st=adminStudents().filter(x=>!q||String(x.matricula).toLowerCase().includes(q)||String(x.nombre).toLowerCase().includes(q));admin$('#catalogAlumnos').innerHTML=st.map(x=>`<tr><td>${escapeHTML(x.matricula)}</td><td>${escapeHTML(x.nombre)}</td><td>${escapeHTML(x.sexo)}</td><td>${escapeHTML(x.carrera)}</td><td>${escapeHTML(x.grupo)}</td><td>${escapeHTML(x.turno)}</td></tr>`).join('')||'<tr><td colspan="6">Sin alumnos.</td></tr>';admin$('#catAlumnosCount').textContent=`${st.length} de ${adminStudents().length} alumno${adminStudents().length===1?'':'s'}`}
function renderCatalogAdvisors(filter=''){const q=filter.toLowerCase(),all=allAdvisors();const us=all.filter(x=>!q||String(x.usuario).toLowerCase().includes(q)||String(x.nombre).toLowerCase().includes(q));admin$('#catalogAsesores').innerHTML=us.map(x=>{const active=x.activo!==false;return `<tr><td>${escapeHTML(x.usuario)}</td><td>${escapeHTML(x.nombre)}</td><td>${x.requierePassword?'Configurada':'No requerida'}</td><td><span class="account-status ${active?'is-active':'is-inactive'}">${active?'Activo':'Inactivo'}</span></td><td><button class="${active?'danger':'secondary'} mini-btn advisor-status-btn" data-user-id="${escapeHTML(x.id)}" data-active="${active?'true':'false'}" data-username="${escapeHTML(x.usuario)}">${active?'Inactivar':'Reactivar'}</button></td></tr>`}).join('')||'<tr><td colspan="5">Sin asesores.</td></tr>';const activeCount=registeredAdvisors().length;admin$('#catAsesoresCount').textContent=`${activeCount} activo${activeCount===1?'':'s'} · ${all.length} total`}
async function toggleAdvisorStatus(button){const active=button.dataset.active==='true',username=button.dataset.username,next=!active,action=next?'reactivar':'inactivar';if(!confirm(`¿Desea ${action} la cuenta de ${username}?${next?'':' El asesor ya no podrá iniciar sesión, pero su historial se conservará.'}`))return;button.disabled=true;const oldText=button.textContent;button.textContent='Guardando...';try{const response=await fetch(`/api/admin/users/${encodeURIComponent(button.dataset.userId)}/active`,{method:'PATCH',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({active:next})});const payload=await response.json();if(!response.ok){alert(payload.message||'No fue posible actualizar la cuenta.');return}await loadAdminData();alert(`La cuenta de ${username} quedó ${next?'activa':'inactiva'}.`)}catch(error){alert('No fue posible comunicarse con el servidor.')}finally{button.disabled=false;button.textContent=oldText}}
function formatPeriodDate(value){const text=String(value||'').slice(0,10),parts=text.split('-');return parts.length===3?`${parts[2]}/${parts[1]}/${parts[0]}`:text}
function renderCatalogPeriods(){const rows=adminPeriods();admin$('#catalogCuatrimestres').innerHTML=rows.map(period=>{const active=period.active!==false;return `<div class="catalog-item period-item"><div class="period-item-info"><strong>${escapeHTML(period.name)}</strong><small>${escapeHTML(formatPeriodDate(period.starts_on))} al ${escapeHTML(formatPeriodDate(period.ends_on))}</small></div><div class="period-actions"><span class="account-status ${active?'is-active':'is-inactive'}">${active?'Activo':'Inactivo'}</span><button class="${active?'danger':'secondary'} mini-btn period-status-btn" data-period-id="${escapeHTML(period.id)}" data-active="${active?'true':'false'}" data-period-name="${escapeHTML(period.name)}">${active?'Inactivar':'Reactivar'}</button></div></div>`}).join('')||'<div class="muted">Sin cuatrimestres registrados.</div>'}
function renderCatalogs(){const c=catalogs();renderCatalogStudents(admin$('#searchAlumnos')?.value||'');renderCatalogAdvisors(admin$('#searchAsesores')?.value||'');renderSimpleCatalog('materias',c.materias,'catalogMaterias');renderSimpleCatalog('carreras',c.carreras,'catalogCarreras');renderSimpleCatalog('grupos',c.grupos,'catalogGrupos');renderSimpleCatalog('motivos',c.motivos,'catalogMotivos');renderCatalogPeriods()}
function renderSimpleCatalog(key,arr,id){admin$(id).innerHTML=arr.filter(x=>x&&x!=='Seleccione').map((x,i)=>`<div class="catalog-item"><span>${escapeHTML(x)}</span><button class="danger mini-btn" data-delete="${key}" data-index="${i}">Eliminar</button></div>`).join('')||'<div class="muted">Sin registros.</div>'}
function addCatalog(key,input){const value=input.value.trim();if(!value)return;let arr=key==='cuatrimestres'?periods():[...(catalogs()[key]||[])];if(!arr.includes(value))arr.push(value);if(key==='cuatrimestres')adminWrite(ADMIN_KEYS.periods,arr);else{const c=catalogs();c[key]=arr;adminWrite(ADMIN_KEYS.catalogs,c)}input.value='';fillAdminFilters();fillPeriodSelect('dashboardPeriod',false);renderAll()}
function deleteCatalog(key,index){if(!confirm('¿Desea quitar este elemento del catálogo?'))return;if(key==='cuatrimestres'){const arr=periods();arr.splice(index,1);adminWrite(ADMIN_KEYS.periods,arr)}else{const c=catalogs();c[key].splice(index,1);adminWrite(ADMIN_KEYS.catalogs,c)}fillAdminFilters();fillPeriodSelect('dashboardPeriod',false);renderAll()}
async function savePeriod(event){event?.preventDefault();const form=admin$('#add-cuatrimestres'),name=admin$('#newPeriodName').value.trim(),startsOn=admin$('#newPeriodStart').value,endsOn=admin$('#newPeriodEnd').value,message=admin$('#periodFormMessage'),button=admin$('#savePeriodBtn');message.textContent='';message.className='advisor-form-message';if(!name||!startsOn||!endsOn){message.textContent='Capture el nombre y ambas fechas.';message.classList.add('error');return}button.disabled=true;button.textContent='Guardando...';try{const response=await fetch('/api/admin/periods',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({name,startsOn,endsOn})});const payload=await response.json();if(!response.ok){message.textContent=payload.message||'No fue posible guardar el cuatrimestre.';message.classList.add('error');return}form.reset();await loadAdminData();message.textContent=`Cuatrimestre ${name} guardado en PostgreSQL.`;message.classList.add('success')}catch(error){message.textContent='No fue posible comunicarse con el servidor.';message.classList.add('error')}finally{button.disabled=false;button.textContent='Guardar'}}
async function togglePeriodStatus(button){const active=button.dataset.active==='true',next=!active,name=button.dataset.periodName,action=next?'reactivar':'inactivar';if(!confirm(`¿Desea ${action} el cuatrimestre ${name}?${next?'':' Los registros históricos se conservarán.'}`))return;button.disabled=true;const oldText=button.textContent;button.textContent='Guardando...';try{const response=await fetch(`/api/admin/periods/${encodeURIComponent(button.dataset.periodId)}/active`,{method:'PATCH',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({active:next})});const payload=await response.json();if(!response.ok){alert(payload.message||'No fue posible actualizar el cuatrimestre.');return}await loadAdminData();alert(`El cuatrimestre ${name} quedó ${next?'activo':'inactivo'}.`)}catch(error){alert('No fue posible comunicarse con el servidor.')}finally{button.disabled=false;button.textContent=oldText}}
function renderAll(){renderDashboard();renderStatistics();renderStudentSummary();renderCatalogs();renderAdminReport()}
function exportExcel(){const rows=getAdminFiltered(),head=['Fecha','Inicio','Fin','Matrícula','Alumno','Sexo','Carrera','Grupo','Materia','Motivo','Comentarios','Asesor','Duración','Psicopedagogía','Cuatrimestre'];const cell=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');const html=`<!doctype html><html><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:Arial;font-size:10pt}th,td{border:1px solid #888;padding:5px}th{font-weight:bold;background:#eee}</style></head><body><table><thead><tr>${head.map(h=>`<th>${cell(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(x=>[x.fecha,x.inicio,x.fin,x.matricula,x.nombre,x.sexo,x.carrera,x.grupo,x.materia,x.motivo,x.comentarios,x.asesor,fmtAdmin(x.duracionMinutos),x.psico,x.periodo]).map(r=>`<tr>${r.map(v=>`<td>${cell(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel;charset=utf-8'}));a.download='reporte_asesorias_excel.xls';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}


function exportStatsExcel(){
  renderStatistics();
  const period=selectedPeriod();
  const xmlEscape=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  const sheetName=v=>String(v).replace(/[\\\/?*\[\]:]/g,' ').slice(0,31)||'Hoja';
  const tableData=(tbodyId,headers)=>{
    const body=admin$(tbodyId);
    const rows=body?Array.from(body.querySelectorAll('tr')).map(tr=>Array.from(tr.querySelectorAll('th,td')).map(td=>td.textContent.trim())):[];
    return [headers,...rows.filter(r=>r.length)];
  };
  const sheets=[
    ['Horas por materia',tableData('bySubject',['Materia','Asesorías','Horas'])],
    ['Asesorías por motivo',tableData('byReason',['Motivo','Asesorías','Horas'])],
    ['Asesorías por asesor',tableData('byAdvisor',['Asesor','Asesorías','Horas'])],
    ['Carrera y grupo',tableData('byGroup',['Carrera','Grupo','Asesorías','Horas'])],
    ['Canalizaciones',tableData('byReferral',['Resultado','Asesorías','Horas'])],
    ['Por cuatrimestre',tableData('byPeriod',['Cuatrimestre','Asesorías','Horas'])]
  ];
  const worksheet=(name,rows)=>`<Worksheet ss:Name="${xmlEscape(sheetName(name))}"><Table>${rows.map((row,ri)=>`<Row>${row.map(value=>`<Cell${ri===0?' ss:StyleID="Header"':''}><Data ss:Type="String">${xmlEscape(value)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet>`;
  const workbook=`<?xml version="1.0"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><DocumentProperties xmlns="urn:schemas-microsoft-com:office:office"><Title>Estadísticas de asesorías</Title><Subject>${xmlEscape(period)}</Subject></DocumentProperties><Styles><Style ss:ID="Default" ss:Name="Normal"><Alignment ss:Vertical="Bottom"/><Font ss:FontName="Arial" ss:Size="10"/></Style><Style ss:ID="Header"><Font ss:FontName="Arial" ss:Size="10" ss:Bold="1"/><Interior ss:Color="#E7E7E7" ss:Pattern="Solid"/></Style></Styles>${sheets.map(([name,rows])=>worksheet(name,rows)).join('')}</Workbook>`;
  const blob=new Blob(['\ufeff'+workbook],{type:'application/vnd.ms-excel;charset=utf-8'});
  const a=document.createElement('a');
  a.href=URL.createObjectURL(blob);
  a.download=`estadisticas_asesorias_${String(period).replace(/[^a-z0-9áéíóúñ_-]+/gi,'_')}.xls`;
  a.click();
  setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}

function printReport(){const rows=getAdminFiltered(),cfg=schoolConfig(),period=admin$('#adminPeriodFilter').value;const table=rows.map(x=>`<tr><td>${escapeHTML(x.fecha)}</td><td>${escapeHTML(x.inicio)}</td><td>${escapeHTML(x.fin)}</td><td>${escapeHTML(x.matricula)}</td><td>${escapeHTML(x.nombre)}</td><td>${escapeHTML(x.sexo)}</td><td>${escapeHTML(x.carrera)}</td><td>${escapeHTML(x.grupo)}</td><td>${escapeHTML(x.materia)}</td><td>${escapeHTML(x.motivo)}</td><td>${escapeHTML(x.comentarios)}</td><td>${escapeHTML(x.asesor)}</td><td>${fmtAdmin(x.duracionMinutos)}</td><td>${escapeHTML(x.psico)}</td></tr>`).join('');admin$('#adminPrintReport').innerHTML=`<div class="print-header"><div class="print-logo">LOGO IZQ.</div><div class="print-school"><h1>${escapeHTML(cfg.schoolName)}</h1><div>REGISTRO DE ASESORÍAS · ${escapeHTML(period==='all'?'Todos los cuatrimestres':period)}</div></div><div class="print-logo">LOGO DER.</div></div><div class="print-advisor"><strong>Reporte administrativo</strong><br>Registros: ${rows.length} · Horas: ${(rows.reduce((t,x)=>t+(Number(x.duracionMinutos)||0),0)/60).toFixed(2)}</div><table id="printTable"><thead><tr><th>Fecha</th><th>Inicio</th><th>Fin</th><th>Matrícula</th><th>Alumno</th><th>Sexo</th><th>Carrera</th><th>Grupo</th><th>Materia</th><th>Motivo</th><th>Comentarios</th><th>Asesor</th><th>Duración</th><th>Psico.</th></tr></thead><tbody>${table}</tbody></table>`;window.print()}
function applySchool(){const cfg=schoolConfig();const school=admin$('#adminSchoolName');if(school)school.textContent=cfg.schoolName;const schoolSetting=admin$('#schoolNameSetting');if(schoolSetting)schoolSetting.value=cfg.schoolName;const footerSetting=admin$('#footerSetting');if(footerSetting)footerSetting.value=cfg.footer;const versionSetting=admin$('#versionSetting');if(versionSetting)versionSetting.value=cfg.version;const footer=admin$('#adminFooterText');if(footer)footer.textContent=cfg.footer;const version=admin$('#adminVersion');if(version)version.textContent=`Versión ${cfg.version} · Administración`}

function showAdminLogin(){admin$('#adminLoginScreen').style.display='flex';document.body.classList.add('locked')}
function hideAdminLogin(){admin$('#adminLoginScreen').style.display='none';document.body.classList.remove('locked')}
function setAdminMessage(message){admin$('#adminLoginMsg').textContent=message||''}
async function loadAdminData(){
  const previousDashboardPeriod=centralAdminData?admin$('#dashboardPeriod')?.value:'';
  const response=await fetch('/api/admin/data?refresh='+Date.now(),{cache:'no-store',headers:{Accept:'application/json'}});
  if(response.status===401||response.status===403){showAdminLogin();return false}
  if(!response.ok)throw new Error('database_error');
  const payload=await response.json(),d=payload.data,c=d.catalogs;
  const rows=(d.advisories||[]).map(x=>{const start=new Date(x.inicioIso),end=new Date(x.finIso);return{...x,fecha:start.toLocaleDateString('es-MX'),inicio:start.toLocaleTimeString('es-MX'),fin:end.toLocaleTimeString('es-MX')}});
  centralAdminData={advisories:rows,students:d.students||[],users:d.users||[],periods:d.periodsAdmin||[]};
  const cat={materias:(c.subjects||[]).map(x=>x.name),carreras:(c.careers||[]).map(x=>x.code),grupos:(c.groups||[]).map(x=>x.name),motivos:(c.reasons||[]).map(x=>x.name)};
  localStorage.setItem(ADMIN_KEYS.catalogs,JSON.stringify(cat));localStorage.setItem(ADMIN_KEYS.periods,JSON.stringify((d.periodsAdmin||c.periods||[]).map(x=>x.name)));
  localStorage.setItem(ADMIN_KEYS.school,JSON.stringify({schoolName:c.school?.school_name||'NOMBRE DE LA INSTITUCIÓN',footer:c.school?.footer_text||'© 2025 Registro de Asesorías Académicas. Todos los derechos reservados.',version:'1.6.0'}));
  if(payload.user){admin$('#adminCurrentUser').textContent='Administrador: '+payload.user.usuario;const account=centralAdminData.users.find(x=>x.usuario.toLowerCase()===payload.user.usuario.toLowerCase());admin$('#securityMsg').textContent=account&&!account.recuperacionConfigurada?'Importante: configure una clave de recuperación antes de cerrar la sesión.':''}
  applySchool();fillPeriodSelect('dashboardPeriod',false);if(!previousDashboardPeriod)admin$('#dashboardPeriod').value=activePeriodName();fillAdminFilters();renderAll();return true;
}
async function adminLogin(){setAdminMessage('Verificando acceso...');try{const response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:admin$('#adminLoginUser').value.trim(),password:admin$('#adminLoginPassword').value,area:'admin'})});const payload=await response.json();if(!response.ok){setAdminMessage(payload.message||'No fue posible ingresar.');return}hideAdminLogin();setAdminMessage('');await loadAdminData()}catch(error){setAdminMessage('No fue posible comunicarse con el servidor.')}}
async function checkAdminSession(){try{const response=await fetch('/api/admin/session');if(!response.ok){showAdminLogin();return false}const payload=await response.json();admin$('#adminCurrentUser').textContent='Administrador: '+payload.user.usuario;hideAdminLogin();await loadAdminData();return true}catch(error){showAdminLogin();setAdminMessage('No fue posible comunicarse con el servidor.');return false}}
async function adminLogout(){try{await fetch('/api/admin/logout',{method:'POST'})}catch(error){}centralAdminData=null;showAdminLogin();admin$('#adminLoginPassword').value='';setAdminMessage('Sesión cerrada.')}
async function recoverAdminAccess(){setAdminMessage('Verificando recuperación...');try{const response=await fetch('/api/admin/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:admin$('#recoveryUser').value.trim(),recoveryCode:admin$('#recoveryCode').value,newPassword:admin$('#recoveryNewPassword').value})});const payload=await response.json();setAdminMessage(payload.message||'');if(response.ok){admin$('#adminRecoveryForm').hidden=true;admin$('#adminLoginForm').hidden=false;admin$('#adminLoginUser').value=admin$('#recoveryUser').value;admin$('#adminLoginPassword').value=''}}catch(error){setAdminMessage('No fue posible comunicarse con el servidor.')}}
async function saveAdminSecurity(){const currentPassword=admin$('#currentAdminPassword').value,newPassword=admin$('#newAdminPassword').value,confirmPassword=admin$('#confirmAdminPassword').value,recoveryCode=admin$('#newRecoveryCode').value,msg=admin$('#securityMsg');if(newPassword!==confirmPassword){msg.textContent='Las contraseñas nuevas no coinciden.';return}msg.textContent='Guardando...';try{const response=await fetch('/api/admin/security',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword,newPassword,recoveryCode})});const payload=await response.json();msg.textContent=payload.message||'';if(response.ok){['currentAdminPassword','newAdminPassword','confirmAdminPassword','newRecoveryCode'].forEach(id=>admin$(id).value='');await loadAdminData();msg.textContent=payload.message||'Seguridad actualizada.'}}catch(error){msg.textContent='No fue posible comunicarse con el servidor.'}}

document.addEventListener('DOMContentLoaded',async()=>{
  admin$('#adminLoginBtn').addEventListener('click',adminLogin);admin$('#adminLoginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')adminLogin()});
  admin$('#showRecoveryBtn').addEventListener('click',()=>{admin$('#adminLoginForm').hidden=true;admin$('#adminRecoveryForm').hidden=false;admin$('#recoveryUser').value=admin$('#adminLoginUser').value;setAdminMessage('')});
  admin$('#backToLoginBtn').addEventListener('click',()=>{admin$('#adminRecoveryForm').hidden=true;admin$('#adminLoginForm').hidden=false;setAdminMessage('')});
  admin$('#recoverAccessBtn').addEventListener('click',recoverAdminAccess);admin$('#adminLogoutBtn').addEventListener('click',adminLogout);admin$('#saveAdminSecurityBtn').addEventListener('click',saveAdminSecurity);
  __requestShared();
  __sharedTimer=setInterval(__requestShared,1500);
  if(!localStorage.getItem(ADMIN_KEYS.catalogs))adminWrite(ADMIN_KEYS.catalogs,defaultCatalogs);
  if(!localStorage.getItem(ADMIN_KEYS.periods))adminWrite(ADMIN_KEYS.periods,[ADMIN_DEFAULT_PERIOD]);
  applySchool();fillPeriodSelect('dashboardPeriod',false);fillAdminFilters();
  const dashboardPeriod=admin$('#dashboardPeriod');
  dashboardPeriod.addEventListener('change',()=>{const p=dashboardPeriod.value;admin$('#adminPeriodFilter').value=p;renderAll()});
  const catalogNames={
    'cat-alumnos':'Alumnos','cat-asesores':'Asesores','cat-materias':'Materias','cat-carreras':'Carreras',
    'cat-grupos':'Grupos','cat-motivos':'Motivos','cat-cuatrimestres':'Cuatrimestres'
  };
  renderAll();
  showCatalog('cat-alumnos');
  ['adminPeriodFilter','adminRangeFilter','adminAdvisorFilter','adminCareerFilter','adminGroupFilter','adminSubjectFilter','adminReasonFilter'].forEach(id=>admin$(id).addEventListener('change',renderAdminReport));
  admin$('#adminStudentSearch').addEventListener('input',renderAdminReport);
  admin$('#printReportBtn').addEventListener('click',printReport);admin$('#exportExcelBtn').addEventListener('click',exportExcel);admin$('#exportStatsExcelBtn')?.addEventListener('click',exportStatsExcel);
  function showCatalog(target){
    document.querySelectorAll('.catalog-panel').forEach(panel=>panel.classList.toggle('is-hidden',panel.id!==target));
    document.querySelectorAll('.admin-catalog-nav button').forEach(btn=>btn.classList.toggle('catalog-active',btn.dataset.target===target));
    const current=admin$('#catalogCurrent');
    if(current) current.innerHTML=`Catálogo seleccionado: <strong>${escapeHTML(catalogNames[target]||'')}</strong>`;
    admin$(target)?.scrollIntoView({behavior:'smooth',block:'start'});
  }
  document.querySelectorAll('.admin-catalog-nav button').forEach(b=>b.addEventListener('click',()=>showCatalog(b.dataset.target)));
  document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{
    const row=admin$(`#add-${b.dataset.add}`);
    if(row){row.classList.toggle('visible'); if(row.classList.contains('visible')) row.querySelector('input')?.focus();}
  }));
  document.querySelectorAll('.catalog-add-row:not(#add-asesores):not(#add-cuatrimestres) button').forEach(b=>b.addEventListener('click',()=>{const row=b.parentElement;addCatalog(row.id.replace('add-',''),row.querySelector('input'))}));
  admin$('#add-cuatrimestres')?.addEventListener('submit',savePeriod);
  admin$('#searchAlumnos').addEventListener('input',e=>renderCatalogStudents(e.target.value));admin$('#searchAsesores').addEventListener('input',e=>renderCatalogAdvisors(e.target.value));admin$('#add-asesores')?.addEventListener('submit',saveAdvisor);
  admin$('#catalogAsesores')?.addEventListener('click',event=>{const button=event.target.closest('.advisor-status-btn');if(button)toggleAdvisorStatus(button)});
  admin$('#catalogCuatrimestres')?.addEventListener('click',event=>{const button=event.target.closest('.period-status-btn');if(button)togglePeriodStatus(button)});
  admin$('#syncDataBtn')?.addEventListener('click',async()=>{try{await loadAdminData();alert('Datos actualizados desde PostgreSQL.')}catch(error){alert('No fue posible actualizar los datos.')}});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(b)deleteCatalog(b.dataset.delete,Number(b.dataset.index))});
  await checkAdminSession();
});
